### ISSUE TITLE
Translating request

### ISSUE THREAD

**Issue by DawnEve** [knpuniversity/symfony#14]
Hi, I am a Chinese student, and I really love your video course that I decide to translate it into Chinese. I wonder if you could give me the permission

**Comment by DawnEve** [comment]
my translating project is Forked at https://github.com/DawnEve/symfony

**Comment by weaverryan** [comment]
Hey @DawnEve! That's really cool! And yea, I would be honored if you translated to Chinese :). I've just pushed a LICENSE file to the repo, which allows you to do that (http://creativecommons.org/licenses/by-nc-sa/4.0/). Keep me updated on your progress - it's very interesting and cool to see!
