### ISSUE TITLE
Add cache refresh note

### ISSUE THREAD

**Issue by weaverryan** [knpuniversity/symfony#15]
@Leannapelham I need a favor!

To this chapter: https://knpuniversity.com/screencast/symfony/layout-assets

At 4:30, right when we refresh the browser, we need to add a note to help something that's tricking up several people:

> If your page is still ugly, make any small change to base.html.twig and
> show.html.twig then refresh again. Don't worry about this: it's due to a
> one-time quirk because you're copying _older_ files from me.

Thanks!

**Comment by weaverryan** [comment]
ping @Leannapelham 

This consistently trips up users. Can you add the note when you have a chance :)

**Comment by Leannapelham** [comment]
updated!
