### ISSUE TITLE
Add a note about install the "PHP Annotations" Plugin

### ISSUE THREAD

**Issue by weaverryan** [knpuniversity/symfony#17]
On this page: http://knpuniversity.com/screencast/symfony/phpstorm-git

At around :55, we need to add this video note:

> You should also find and install the "PHP Annotations" plugin. That will give
> you the awesome annotations auto-completion that you'll see in the video.

**Comment by bocharsky-bw** [comment]
Actually, we already have this note, I've just tweaked it in https://github.com/knpuniversity/symfony/commit/775b949c772806f6ddc1fff393fa4ec0694c22a9

**Comment by Leannapelham** [comment]
@bocharsky-bw - Oh good catch on adding it to the script - - I'll plug in a note to the video as well.
